apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-deployment
spec:
  replicas: 1  # Number of desired replicas
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
      - name: react-app
        image: monikavcube/react-app:latest  # Added space after the colon
        ports:
        - containerPort: 3000  # Port your application listens on
